function getDegrees() {
  return [
    "Bachelor of Architecture",
    "Bachelor of Arts",
    "Bachelor of Applied Arts",
    "Bachelor of Applied Arts & Science",
    "Bachelor of Applied Science in Information Technology",
    "Bachelor of Design",
    "Bachelor of Engineering",
    "Bachelor of Science in Business",
    "Bachelor of Engineering Technology",
    "Bachelor of Technology",
    "International Business Economics",
    "Bachelor of Business Administration",
    "Bachelor of Management Studies",
    "Bachelor of Administrative Studies",
    "Bachelor of International Business Economics",
    "Bachelor of Commerce",
    "Bachelor of Fine Arts",
    "Bachelor of Business",
    "Bachelor of Management & Organizational Studies",
    "Bachelor of Business Science",
    "Bachelor of Accountancy",
    "Bachelor of Economics",
    "Bachelor of Arts in Organizational Management",
    "Bachelor of Computer Science",
    "Bachelor of Computing",
    "Bachelor of Science in Information Technology",
    "Bachelor of Computer Applications",
    "Bachelor of Business Information Systems",
    "Intercalated Bachelor of Science",
    "Bachelor of Medical Science",
    "Bachelor of Medical Biology",
    "Bachelor of Science in Public Health",
    "Bachelor of Science in Nursing",
    "Bachelor of Health Science",
    "Bachelor of Kinesiology",
    "Bachelor of Arts for Teaching",
    "Bachelor of Aviation",
    "Bachelor of Film & Television",
    "Bachelor of Integrated studies",
    "Bachelor of Journalism",
    "Bachelor of Landscape Architecture",
    "Bachelor of Liberal Arts",
    "Bachelor of General Studies",
    "Bachelor of Science in Human Biology",
    "Bachelor of Applied Studies",
    "Bachelor of Liberal Studies",
    "Bachelor of Professional Studies",
    "Bachelor of Library Science",
    "Bachelor of Library & Information Science",
    "Bachelor of Music",
    "Bachelor of Art in Music",
    "Bachelor of Music Education",
    "Bachelor of Philosophy",
    "Bachelor of Arts in Psychology",
    "Bachelor of Mortuary Science",
    "Bachelor of Science in Psychology",
    "Bachelor of Science in Education",
    "Bachelor of Science in Forestry",
    "Bachelor of Applied Science",
    "Bachelor of Science in Law",
    "Bachelor of Social Science",
    "Bachelor of Arts in Social Work",
    "Bachelor of Talmudic Law",
    "Bachelor of Technology",
    "Bachelor of Tourism Studies",
    "Bachelor of Mathematics",
    "Bachelor of Mathematical Sciences",
    "Bachelor of Public Affairs & Policy Management",
    "Bachelor of Urban & Regional Planning",
  ];
}

module.exports = getDegrees;
