function getHobbies() {
  return [
    "3D printing",
    "Acting",
    "Action figure",
    "Air sports",
    "Aircraft spotting",
    "Airsoft",
    "Amateur astronomy",
    "Amateur radio",
    "American football",
    "Animal fancy",
    "Antiquing",
    "Antiquities",
    "Archery",
    "Art collecting",
    "Association football",
    "Astrology",
    "Astronomy",
    "Australian rules football",
    "Auto audiophilia",
    "Auto racing",
    "BASE jumping",
    "Badminton",
    "Baseball",
    "Basketball",
    "Baton Twirling",
    "Baton twirling",
    "Beach Volleyball",
    "Beekeeping",
    "Billiards",
    "Bird watching",
    "Birdwatching",
    "Blacksmithing",
    "Board games",
    "Board sports",
    "Bodybuilding",
    "Book collecting",
    "Book restoration",
    "Bowling",
    "Boxing",
    "Brazilian jiu-jitsu",
    "Breakdancing",
    "Bridge",
    "Bus spotting",
    "Cabaret",
    "Calligraphy",
    "Camping",
    "Candle making",
    "Card collecting",
    "Cheerleading",
    "Chess",
    "Climbing",
    "Coffee roasting",
    "Coin collecting",
    "Color guard",
    "Coloring",
    "Comic book collecting",
    "Computer programming",
    "Cooking",
    "Cosplaying",
    "Couponing",
    "Creative writing",
    "Cricket",
    "Crocheting",
    "Cross-stitch",
    "Crossword puzzles",
    "Cryptography",
    "Curling",
    "Cycling",
    "Dance",
    "Dancing",
    "Darts",
    "Debate",
    "Deltiology (postcard collecting)",
    "Die-cast toy",
    "Digital arts",
    "Disc golf",
    "Do it yourself",
    "Dog sport",
    "Dowsing",
    "Drama",
    "Drawing",
    "Driving",
    "Electronics",
    "Element collecting",
    "Embroidery",
    "Equestrianism",
    "Exhibition drill",
    "Fantasy Sports",
    "Fashion",
    "Fencing",
    "Field hockey",
    "Figure skating",
    "Fishing",
    "Fishkeeping",
    "Flag football",
    "Flower arranging",
    "Flower collecting and pressing",
    "Flying",
    "Flying disc",
    "Footbag",
    "Foraging",
    "Foreign language learning",
    "Fossil hunting",
    "Freestyle football",
    "Gaming (tabletop games and role-playing games)",
    "Gardening",
    "Genealogy",
    "Geocaching",
    "Ghost hunting",
    "Glassblowing",
    "Go",
    "Golfing",
    "Gongoozling",
    "Graffiti",
    "Gunsmithing",
    "Gymnastics",
    "Handball",
    "Herping",
    "High-Powered Rocketry",
    "Hiking",
    "Hiking/backpacking",
    "Homebrewing",
    "Hooping",
    "Horseback riding",
    "Hunting",
    "Hydroponics",
    "Ice hockey",
    "Ice skating",
    "Inline skating",
    "Insect collecting",
    "Jewelry making",
    "Jigsaw puzzles",
    "Jogging",
    "Judo",
    "Juggling",
    "Jukskei",
    "Kabaddi",
    "Kart racing",
    "Kayaking",
    "Kite flying",
    "Kitesurfing",
    "Knapping",
    "Knife making",
    "Knife throwing",
    "Knitting",
    "Kombucha Brewing",
    "LARPing",
    "Lacemaking",
    "Lacrosse",
    "Lapidary",
    "Laser tag",
    "Learning",
    "Leather crafting",
    "Lego building",
    "Letterboxing",
    "Listening to music",
    "Lockpicking",
    "Machining",
    "Macrame",
    "Magic",
    "Mahjong",
    "Marbles",
    "Martial arts",
    "Metal detecting",
    "Metalworking",
    "Meteorology",
    "Microscopy",
    "Mineral collecting",
    "Model aircraft",
    "Model building",
    "Motor sports",
    "Mountain biking",
    "Mountaineering",
    "Movie and movie memorabilia collecting",
    "Mushroom hunting/Mycology",
    "Netball",
    "Nordic skating",
    "Orienteering",
    "Origami",
    "Paintball",
    "Painting",
    "Parkour",
    "People watching",
    "Pet",
    "Philately",
    "Photography",
    "Pigeon racing",
    "Plastic embedding",
    "Playing musical instruments",
    "Pleasuring",
    "Poi",
    "Poker",
    "Polo",
    "Pottery",
    "Puzzles",
    "Quilling",
    "Quilting",
    "Racquetball",
    "Radio-controlled car racing",
    "Rafting",
    "Rappelling",
    "Reading",
    "Record collecting",
    "Road biking",
    "Rock balancing",
    "Rock climbing",
    "Roller derby",
    "Roller skating",
    "Rugby",
    "Rugby league football",
    "Running",
    "Sailing",
    "Sand art",
    "Satellite watching",
    "Scouting",
    "Scrapbooking",
    "Scuba diving",
    "Sculling or Rowing",
    "Sculpting",
    "Sea glass collecting",
    "Seashell collecting",
    "Sewing",
    "Shooting",
    "Shooting sport",
    "Shopping",
    "Shortwave listening",
    "Singing",
    "Skateboarding",
    "Sketching",
    "Skiing",
    "Skimboarding",
    "Skydiving",
    "Slacklining",
    "Slot car racing",
    "Snowboarding",
    "Soapmaking",
    "Soccer",
    "Speed skating",
    "Speedcubing",
    "Sport stacking",
    "Squash",
    "Stamp collecting",
    "Stand-up comedy",
    "Stone collecting",
    "Stone skipping",
    "Surfing",
    "Swimming",
    "Table football",
    "Table tennis",
    "Taekwondo",
    "Tai chi",
    "Tatting",
    "Tennis",
    "Topiary",
    "Tour skating",
    "Trainspotting",
    "Traveling",
    "Triathlon",
    "Ultimate Disc",
    "Urban exploration",
    "Vacation",
    "Vehicle restoration",
    "Video game collecting",
    "Video gaming",
    "Videophilia",
    "Vintage cars",
    "Volleyball",
    "Walking",
    "Watching movies",
    "Watching television",
    "Water sports",
    "Web surfing",
    "Weightlifting",
    "Whale watching",
    "Whittling",
    "Wikipedia editing",
    "Wood carving",
    "Woodworking",
    "Worldbuilding",
    "Writing",
    "Yo-yoing",
    "Yoga",
  ];
}

module.exports = getHobbies;
